# Use an official Node.js runtime as the base image
FROM node:16-alpine
# Set the working directory in the container
WORKDIR /app
# Copy package.json and package-lock.json to the working directory
COPY demos-origins/node-app/package*.json ./
# Install Node.js dependencies
RUN npm install
# Copy the rest of the application code to the working directory
COPY demos-origins/node-app/. .
# Expose the application port
EXPOSE 3009
# Start the Node.js application
CMD ["npm", "run", "serve"]