apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: wf-front-secret-dev
  namespace: dev
spec:
  encryptedData:
    env_file: AgBqgVXwmxtCUUvH2CzT2cClJwVLP0Py8vrkEEmvBdPIhmDEX432y+8DzLkbHOrW0GcMrTmsKyHOfXY35c3gzyyp3EIsEzKhSR28QRR1RdI/kcoaA9a3jhwUuC/j6PAEWIns9zsUENghddABTNf1yYHqbb/RlruGKCvvFYRev0jazx8PAdtz5M7JDC1q2JXw5Y0Bf7HQRGnkolw3ruzVKL4zEYc02Cp31TgbL4xziHkDg6jYMXfGIh/RByaoopjxvhHnfL6qwh8w+T6LBL+Nd9LuutzTjVLxLfoDoE8/kfEuw+NQrTgT+CL/raiSQ8Xlx19YPqhRBSdLWpSgHEhJPcGksOE3sev/v+MfUJaJyoqL/UiKhV1BAWlI20Ws8WADVXJxjm0mJeDxApc3WA4+rKA6CGgRji8Kpu644VxThcaqB9kC9AtL9+eh3YjP38tM8Jkm6+cU2BPYgLyWrY/DL/MhT85PWf0vO780QFA+RWz4b+4fRO8xQ+zicciyrDhvTDbS3RlKimWHP8uTaom59USV2IbAtgK8q6+c6Iz/ifdQVwCn/AYVyRArP7v8DpPfED+AiNQm++ULV7IA1hT1Dzi416kAWPM1BW3KpVXMioHpeV2yvxUlPRzsiLXtSLG8FIK7CBQCiSJe1PFN+enQAYLYII0v3MZ/IEGGhrP7ZI04WKzuSX7y9vfIdl8u7BbCbCGuHUgZy+Kihhh0SDnOJa2mDIWz9esTyTTf7fitsivqWkdC3QwWnoIIFQaXeAc36gGen/7mIzyQU7pRZTRgR8A3eM/b1c4Tt0iI3KOEh8VzznP+cqyS8XAAKQLaVKycCV3HeWTjdLHqQE7QdHu5gBAYKqPL/vEJ4iicRpZq9QwzC9ejIQzG8EZ0tk1QRhc87a3pWmRp2yd+YMYB6iachKkZho0UZHNXw4ndm0JcvwAe3sS9feIXRSU3jy39aEMByf5OsauDOZyd5g+g3F7jdb7dkj4L+dwKoe2dtAPX7ctsNFU3nl+F3dbpSFWqHZThl8FXM8+4NY0XU3woBjsuOPtFcQktfn5yvl4Z3y5B+oYSFjYpDmUOTZ9y+A==
  template:
    metadata:
      creationTimestamp: null
      name: wf-front-secret-dev
      namespace: dev

