#!/bin/bash
# =============================================================================
# WSLProxy Admin UI - Multi-Environment Dev Launcher
# =============================================================================
# Interactive script for starting the admin UI dev server against different
# API backends. Modeled after the diy-tax-return-uk project pattern.
#
# Usage:
#   ./start.sh                     # Interactive menu
#   ./start.sh --env=local         # Local dev (Docker API on localhost:8280)
#   ./start.sh --env=lan           # LAN dev (auto-detect IP, bind 0.0.0.0)
#   ./start.sh --env=int           # Point at int.wslproxy.com
#   ./start.sh --env=prod          # Point at wslproxy.com (production!)
#   ./start.sh --env=diytaxreturn  # Point at pop.diytaxreturn.co.uk
#   ./start.sh --ci --env=int      # CI mode (no prompts, no color)
#   ./start.sh --help              # Show help
# =============================================================================

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ADMIN_DIR="$SCRIPT_DIR/openresty-admin"
CI_MODE=false
ENV_MODE=""

show_help() {
    echo -e "${GREEN}${BOLD}WSLProxy Admin UI - Multi-Environment Dev Launcher${NC}"
    echo ""
    echo -e "${CYAN}Usage:${NC}"
    echo "  ./start.sh [OPTIONS]"
    echo ""
    echo -e "${CYAN}Options:${NC}"
    echo "  --env=ENV       Set environment mode directly"
    echo "  --ci            CI mode (no prompts, no color output)"
    echo "  --help, -h      Show this help message"
    echo ""
    echo -e "${CYAN}Environment Modes:${NC}"
    echo "  local           Local dev against Docker API (localhost:8280)"
    echo "  lan             LAN dev with auto-detected IP (0.0.0.0 binding)"
    echo "  int             Integration (int.wslproxy.com)"
    echo "  prod            Production (wslproxy.com) - use with caution!"
    echo "  diytaxreturn    DIY Tax Return (pop.diytaxreturn.co.uk)"
    echo ""
    echo -e "${CYAN}Examples:${NC}"
    echo "  ./start.sh                          # Interactive menu"
    echo "  ./start.sh --env=local              # Quick start local dev"
    echo "  ./start.sh --env=lan                # LAN testing (mobile, etc.)"
    echo "  ./start.sh --env=int                # Develop against int API"
    echo "  ./start.sh --ci --env=int           # CI mode, no prompts"
    echo ""
    echo -e "${CYAN}Equivalent npm commands (from openresty-admin/):${NC}"
    echo "  npm run dev                         # Same as --env=local"
    echo "  npm run dev:lan                     # Same as --env=lan"
    echo "  npm run dev:int                     # Same as --env=int"
    echo "  npm run dev:prod                    # Same as --env=prod"
    echo "  npm run dev:diytaxreturn            # Same as --env=diytaxreturn"
    echo ""
    echo -e "${CYAN}Notes:${NC}"
    echo "  - For Docker-based full-stack dev, use ./dev.sh instead"
    echo "  - Env files: openresty-admin/.env.* (see .env.example for docs)"
    echo "  - Local overrides: create .env.local or .env.<mode>.local (gitignored)"
    echo ""
}

log_info() {
    if $CI_MODE; then echo "[INFO] $1"; else echo -e "${GREEN}[+]${NC} $1"; fi
}

log_warn() {
    if $CI_MODE; then echo "[WARN] $1"; else echo -e "${YELLOW}[!]${NC} $1"; fi
}

log_error() {
    if $CI_MODE; then echo "[ERROR] $1" >&2; else echo -e "${RED}[!]${NC} $1" >&2; fi
}

detect_lan_ip() {
    local ip=""
    # macOS
    if command -v ipconfig &>/dev/null; then
        ip=$(ipconfig getifaddr en0 2>/dev/null || ipconfig getifaddr en1 2>/dev/null || true)
    fi
    # Linux fallback
    if [ -z "$ip" ] && command -v hostname &>/dev/null; then
        ip=$(hostname -I 2>/dev/null | awk '{print $1}' || true)
    fi
    # ip command fallback
    if [ -z "$ip" ] && command -v ip &>/dev/null; then
        ip=$(ip route get 1.1.1.1 2>/dev/null | awk '{print $7; exit}' || true)
    fi
    echo "$ip"
}

setup_lan_env() {
    local lan_ip
    lan_ip=$(detect_lan_ip)

    if [ -z "$lan_ip" ]; then
        log_error "Could not auto-detect LAN IP address."
        echo "  Please create openresty-admin/.env.lan.local manually:"
        echo "    VITE_API_URL=http://YOUR_IP:8280/api"
        echo "    VITE_FRONT_URL=http://YOUR_IP:8280"
        exit 1
    fi

    log_info "Detected LAN IP: ${lan_ip}"

    cat > "$ADMIN_DIR/.env.lan.local" << EOF
# Auto-generated by start.sh on $(date '+%Y-%m-%d %H:%M:%S')
# LAN IP: ${lan_ip}
VITE_API_URL=http://${lan_ip}:8280/api
VITE_FRONT_URL=http://${lan_ip}:8280
EOF

    log_info "Generated openresty-admin/.env.lan.local"
    echo ""
    echo -e "  ${CYAN}Access from other devices:${NC}"
    echo -e "  Admin UI:  ${GREEN}http://${lan_ip}:5173${NC}"
    echo -e "  API:       ${GREEN}http://${lan_ip}:8280/api${NC}"
    echo ""
    echo -e "  ${YELLOW}Note: Docker dev environment (./dev.sh) must be running for the API.${NC}"
}

show_menu() {
    echo ""
    echo -e "${CYAN}${BOLD}WSLProxy Admin UI - Environment Selection${NC}"
    echo -e "${CYAN}===========================================${NC}"
    echo ""
    echo -e "  ${BOLD}1)${NC} local          Local dev against Docker API (localhost:8280)"
    echo -e "  ${BOLD}2)${NC} lan            LAN testing with auto-detected IP"
    echo -e "  ${BOLD}3)${NC} int            Integration API (int.wslproxy.com)"
    echo -e "  ${BOLD}4)${NC} prod           Production API (wslproxy.com) ${RED}[caution]${NC}"
    echo -e "  ${BOLD}5)${NC} diytaxreturn   DIY Tax Return API (pop.diytaxreturn.co.uk)"
    echo ""
    echo -e "  ${BOLD}h)${NC} help           Show detailed help"
    echo -e "  ${BOLD}q)${NC} quit           Exit"
    echo ""

    local choice
    read -p "Select environment [1-5, h, q]: " choice

    case "$choice" in
        1|local)        ENV_MODE="local" ;;
        2|lan)          ENV_MODE="lan" ;;
        3|int)          ENV_MODE="int" ;;
        4|prod)         ENV_MODE="prod" ;;
        5|diytaxreturn) ENV_MODE="diytaxreturn" ;;
        h|help)         show_help; exit 0 ;;
        q|quit)         echo "Goodbye."; exit 0 ;;
        *)
            log_error "Invalid choice: $choice"
            show_menu
            return
            ;;
    esac
}

# ── Parse Arguments ──────────────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
    case "$1" in
        --env=*)   ENV_MODE="${1#--env=}"; shift ;;
        --ci)      CI_MODE=true; shift ;;
        -h|--help) show_help; exit 0 ;;
        *)         log_error "Unknown option: $1"; show_help; exit 1 ;;
    esac
done

# ── Interactive Menu ─────────────────────────────────────────────────────────
if [ -z "$ENV_MODE" ]; then
    if $CI_MODE; then
        log_error "CI mode requires --env flag (e.g., --ci --env=int)"
        exit 1
    fi
    show_menu
fi

# ── Validate Environment ─────────────────────────────────────────────────────
case "$ENV_MODE" in
    local|lan|int|prod|diytaxreturn) ;;
    *)
        log_error "Unknown environment: $ENV_MODE"
        log_error "Valid options: local, lan, int, prod, diytaxreturn"
        exit 1
        ;;
esac

# ── Pre-flight Checks ───────────────────────────────────────────────────────
log_info "Environment: $ENV_MODE"

if [ ! -d "$ADMIN_DIR" ]; then
    log_error "Admin directory not found: $ADMIN_DIR"
    exit 1
fi

if ! command -v node &>/dev/null; then
    log_error "Node.js is not installed. Install from https://nodejs.org/"
    exit 1
fi

# Check node_modules
if [ ! -d "$ADMIN_DIR/node_modules" ]; then
    log_warn "node_modules not found. Installing dependencies..."
    cd "$ADMIN_DIR"
    if command -v yarn &>/dev/null; then
        yarn install --network-timeout 300000
    else
        npm install
    fi
    cd "$SCRIPT_DIR"
fi

# ── Production Warning ───────────────────────────────────────────────────────
if [ "$ENV_MODE" = "prod" ] && ! $CI_MODE; then
    echo ""
    echo -e "  ${RED}${BOLD}WARNING: You are about to connect to the PRODUCTION API!${NC}"
    echo -e "  ${RED}API: https://wslproxy.com/api${NC}"
    echo ""
    read -p "  Are you sure? [y/N]: " confirm
    case "$confirm" in
        [yY]|[yY][eE][sS]) ;;
        *) echo "Aborted."; exit 0 ;;
    esac
fi

# ── LAN Mode Setup ──────────────────────────────────────────────────────────
if [ "$ENV_MODE" = "lan" ]; then
    setup_lan_env
fi

# ── Determine Vite Mode ─────────────────────────────────────────────────────
if [ "$ENV_MODE" = "local" ]; then
    VITE_MODE_FLAG=""
    log_info "Using default mode (loads .env + .env.local)"
else
    VITE_MODE_FLAG="--mode $ENV_MODE"
    log_info "Using mode: $ENV_MODE (loads .env + .env.$ENV_MODE)"
fi

# ── Show Environment Info ────────────────────────────────────────────────────
echo ""
ENV_FILE="$ADMIN_DIR/.env"
if [ "$ENV_MODE" != "local" ] && [ -f "$ADMIN_DIR/.env.$ENV_MODE" ]; then
    ENV_FILE="$ADMIN_DIR/.env.$ENV_MODE"
fi
API_URL=$(grep "^VITE_API_URL=" "$ENV_FILE" 2>/dev/null | cut -d'=' -f2- || echo "unknown")
FRONT_URL=$(grep "^VITE_FRONT_URL=" "$ENV_FILE" 2>/dev/null | cut -d'=' -f2- || echo "unknown")

echo -e "  ${CYAN}Configuration:${NC}"
echo -e "  API URL:    ${GREEN}$API_URL${NC}"
echo -e "  Front URL:  ${GREEN}$FRONT_URL${NC}"
echo -e "  Dev server: ${GREEN}http://localhost:5173${NC}"
if [ "$ENV_MODE" = "lan" ]; then
    LAN_IP=$(detect_lan_ip)
    echo -e "  LAN access: ${GREEN}http://${LAN_IP}:5173${NC}"
fi
echo ""

# ── Launch Vite Dev Server ───────────────────────────────────────────────────
log_info "Starting Vite dev server..."
echo ""

cd "$ADMIN_DIR"

if command -v npx &>/dev/null; then
    exec npx vite $VITE_MODE_FLAG
else
    exec ./node_modules/.bin/vite $VITE_MODE_FLAG
fi
