declare namespace NodeJS {
  interface ProcessEnv {
    NEXT_PUBLIC_API_URL?: string;
    NEXT_PUBLIC_FRONT_URL?: string;
    NEXT_PUBLIC_APP_NAME?: string;
    NEXT_PUBLIC_APP_DISPLAY_NAME?: string;
    NEXT_PUBLIC_APP_VERSION?: string;
    NEXT_PUBLIC_APP_BUILD_NUMBER?: string;
    NEXT_PUBLIC_DEPLOYMENT_TIME?: string;
    NEXT_PUBLIC_THEME_PRIMARY_COLOR?: string;
    NEXT_PUBLIC_THEME_SECONDARY_COLOR?: string;
    NEXT_PUBLIC_THEME_HOVER_COLOR?: string;
    NEXT_PUBLIC_TARGET_PLATFORM?: 'DOCKER' | 'KUBERNETES';
    NEXT_PUBLIC_JWT_SECURITY_PASSPHRASE?: string;
  }
}
