- name: Restart openresty
  service:
   name: openresty
   state: restarted
  tags: [ luarocks, openresty ]

- name: Reload systemd
  systemd:
    daemon_reload: yes
  tags: [ luarocks, openresty ]

- name: restart nextjs dashboard
  systemd:
    name: wslproxy-nextjs-dashboard
    state: restarted
    daemon_reload: yes
  tags: [ dashboard-next ]
