#!/bin/bash
# ──────────────────────────────────────────────────────
# WSLProxy Release Script
#
# Updates system/app.json with current build timestamp,
# commits, pushes to main, then creates a PR from main
# to a release-{version} branch.
#
# Usage: bash devops/scripts/release.sh
# ──────────────────────────────────────────────────────
set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
APP_JSON="${REPO_ROOT}/system/app.json"

if [ ! -f "${APP_JSON}" ]; then
    echo "ERROR: ${APP_JSON} not found"
    exit 1
fi

# Check we're on main
CURRENT_BRANCH=$(git branch --show-current)
if [ "${CURRENT_BRANCH}" != "main" ]; then
    echo "ERROR: Must be on 'main' branch (currently on '${CURRENT_BRANCH}')"
    exit 1
fi

# Check for gh CLI
if ! command -v gh &> /dev/null; then
    echo "ERROR: GitHub CLI (gh) is required. Install: https://cli.github.com"
    exit 1
fi

# Check for jq
if ! command -v jq &> /dev/null; then
    echo "ERROR: jq is required. Install: brew install jq"
    exit 1
fi

# Read current version
VERSION=$(jq -r '.version.version' "${APP_JSON}")
echo "Current version: ${VERSION}"

# Generate build timestamp
BUILD_TIMESTAMP=$(date +%Y%m%d%H%M%S)
DEPLOYMENT_ISO=$(date -u +%Y-%m-%dT%H:%M:%SZ)

echo "New build:       ${BUILD_TIMESTAMP}"
echo "Deployment time: ${DEPLOYMENT_ISO}"

# Update app.json
jq --arg build "${BUILD_TIMESTAMP}" \
   --arg deploy "${DEPLOYMENT_ISO}" \
   '.version.build = $build | .version.deployment_timestamp = $deploy' \
   "${APP_JSON}" > "${APP_JSON}.tmp" && mv "${APP_JSON}.tmp" "${APP_JSON}"

echo ""
echo "Updated ${APP_JSON}:"
cat "${APP_JSON}"
echo ""

# Commit and push to main
git add "${APP_JSON}"
if git diff --cached --quiet; then
    echo "No changes to commit (build already up to date)"
else
    git commit -m "Release ${VERSION} build ${BUILD_TIMESTAMP}"
    echo "Committed build update to main"
fi

git push origin main
echo "Pushed main to origin"

# Create release branch
RELEASE_BRANCH="release-${VERSION}"
echo ""
echo "Creating branch: ${RELEASE_BRANCH}"

# Check if release branch exists on remote
if git ls-remote --heads origin "${RELEASE_BRANCH}" | grep -q "${RELEASE_BRANCH}"; then
    echo "Branch ${RELEASE_BRANCH} already exists on remote — updating it"
    git fetch origin "${RELEASE_BRANCH}"
    git checkout "${RELEASE_BRANCH}"
    git merge main --no-edit
    git push origin "${RELEASE_BRANCH}"
    git checkout main
else
    git branch "${RELEASE_BRANCH}" main
    git push origin "${RELEASE_BRANCH}"
    echo "Pushed ${RELEASE_BRANCH} to origin"
fi

# Create PR from main → release branch
echo ""
echo "Creating PR: main → release"

# Check if release branch exists, create if not
if ! git ls-remote --heads origin release | grep -q "refs/heads/release$"; then
    echo "Creating 'release' branch on remote from main"
    git push origin "main:release"
fi

PR_TITLE="Release ${VERSION} (build ${BUILD_TIMESTAMP})"
PR_BODY="$(cat <<EOF
## Release ${VERSION}

**Build:** ${BUILD_TIMESTAMP}
**Branch:** ${RELEASE_BRANCH}

### Changes
$(git log origin/release..main --oneline --no-merges 2>/dev/null || echo "Initial release")

### Deployment
Merging this PR triggers the CI/CD pipeline:
\`int → test → acc → prod (pop0 + lon1)\`

🚀 Generated by \`devops/scripts/release.sh\`
EOF
)"

PR_URL=$(gh pr create \
    --base release \
    --head main \
    --title "${PR_TITLE}" \
    --body "${PR_BODY}" 2>&1) || {
    # PR may already exist
    EXISTING=$(gh pr list --base release --head main --json url --jq '.[0].url' 2>/dev/null)
    if [ -n "${EXISTING}" ]; then
        PR_URL="${EXISTING}"
        echo "PR already exists: ${PR_URL}"
    else
        echo "ERROR: Failed to create PR: ${PR_URL}"
        exit 1
    fi
}

echo ""
echo "============================================"
echo "  Release ${VERSION} ready!"
echo ""
echo "  Build:   ${BUILD_TIMESTAMP}"
echo "  Branch:  ${RELEASE_BRANCH}"
echo "  PR:      ${PR_URL}"
echo ""
echo "  Merge the PR to trigger deployment."
echo "============================================"
