apiVersion: v1
kind: Service
metadata:
  name: {{ include "wslproxy.fullname" . }}-controller-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "wslproxy.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
spec:
  type: LoadBalancer
  ports:
  - name: metrics
    port: {{ .Values.controller.metrics.port }}
    targetPort: metrics
    protocol: TCP
  selector:
    {{- include "wslproxy.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: controller
