name: Build and Push WhiteFalcon Docker Image to Docker Hub

on:
  push:
    branches:
      - 'dummy'
  workflow_dispatch:
    inputs:
      IMAGE_TAG:
        type: choice
        description: 'Please choose the Docker image tag'
        default: 'latest'
        required: true
        options:
        - latest
        - prod
        - test
        - int
        - dev

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWD }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: bwalia/whitefalcon:latest
      -
        name: Build and push node app
        uses: docker/build-push-action@v4
        with:
          file: demos-origins/node-app/Dockerfile
          push: true
          tags: bwalia/node-app:latest
          
          
          