    # Default server configuration
    # This file is overwritten by Ansible template default.conf.j2
    # with the resolved value of nginx_default_server_hostname variable
    #
    server {
        listen       80;
        server_name  _;

       location / {
           return 301 https://$host$request_uri;
       }
    }
