stream {
    upstream str_k3s0_api_9443 {
        least_conn;
        server 192.168.1.124:9443 weight=1 max_fails=2 fail_timeout=10s;
        server 192.168.1.138:9443 weight=1 max_fails=2 fail_timeout=10s;
#        server 192.168.1.121:9443 weight=1 max_fails=2 fail_timeout=10s;
    }
    server {
        listen 9443;
        proxy_pass str_k3s0_api_9443;
        proxy_timeout 10m;
        proxy_connect_timeout 5s;
    }
}