---
# Deploy OpenResty admin UI and build with npm/yarn
# Only runs when nginx_web_ui_enabled == "yes"

- name: Sync openresty-admin files
  ansible.posix.synchronize:
    src: ../../openresty-admin/
    dest: /usr/local/openresty/nginx/html/openresty-admin
  register: sync_admin
  tags: [openresty, lapis, dashboard]

- debug:
    var: sync_admin.stdout_lines
  tags: [openresty, lapis, dashboard]

- name: Copy npm/yarn build script
  template:
    src: install-build-npm-yarn.sh.j2
    dest: /tmp/install-build-npm-yarn.sh
    mode: 0777
  tags: [openresty, lapis, dashboard]

- name: Execute the npm/yarn build script
  shell: /tmp/install-build-npm-yarn.sh
  tags: [openresty, lapis, dashboard]
