---
# RHEL/Rocky/AlmaLinux-specific wslproxy setup tasks

- name: Update dnf cache
  dnf:
    update_cache: yes
  tags: [os_deps, build]

- name: Upgrade all packages
  dnf:
    name: "*"
    state: latest
  tags: [os_deps, build]
