---
# OS-specific variables for Debian/Ubuntu

os_sudo_group: sudo
os_luarocks_package: luarocks

# PAM configuration paths
os_pam_session_file: /etc/pam.d/common-session
os_pam_noninteractive_file: /etc/pam.d/common-session-noninteractive
os_pam_create_file: false

# OpenResty build dependencies
os_build_deps:
  - libpcre3-dev
  - libssl-dev
  - perl
  - make
  - build-essential
  - curl
  - zlib1g-dev
  - wget
  - gcc
  - unzip
