---
# OS-specific variables for RHEL/Rocky/AlmaLinux

os_sudo_group: wheel
os_luarocks_package: luarocks

# PAM configuration paths
os_pam_session_file: /etc/pam.d/system-auth
os_pam_noninteractive_file: ""
os_pam_create_file: false

# OpenResty build dependencies
os_build_deps:
  - pcre-devel
  - openssl-devel
  - perl
  - make
  - gcc
  - wget
  - zlib-devel
