-- Varnish VCL Template Engine for WSL Proxy
-- Handles VCL generation from config + deterministic snippet injection
-- Supports template variable rendering and validation via varnishd -C

local _M = {}

local cjson = require("cjson")

-- ============================================================
-- Base VCL 4.1 Template
-- ============================================================

_M.BASE_TEMPLATE = [[
vcl 4.1;

import std;

# ============================================================
# Backend definition (origin server)
# Auto-generated by WSLProxy Varnish Manager
# ============================================================

backend default {
    .host = "{{backend_host}}";
    .port = "{{backend_port}}";
    .connect_timeout = {{backend_connect_timeout}};
    .first_byte_timeout = {{backend_first_byte_timeout}};
    .between_bytes_timeout = {{backend_between_bytes_timeout}};
{{health_check_block}}
}

# ============================================================
# vcl_init - Initialization
# ============================================================
sub vcl_init {
    # <<WSLPROXY_SNIPPETS:vcl_init>>
}

# ============================================================
# vcl_recv - Request received from client
# ============================================================
sub vcl_recv {
    # <<WSLPROXY_SNIPPETS:vcl_recv>>

    # Default: pass non-cacheable methods
    if (req.method != "GET" && req.method != "HEAD") {
        return (pass);
    }
}

# ============================================================
# vcl_hash - Build cache hash key
# ============================================================
sub vcl_hash {
    hash_data(req.url);
    if (req.http.host) {
        hash_data(req.http.host);
    } else {
        hash_data(server.ip);
    }
    # <<WSLPROXY_SNIPPETS:vcl_hash>>
    return (lookup);
}

# ============================================================
# vcl_hit - Cache hit
# ============================================================
sub vcl_hit {
    # <<WSLPROXY_SNIPPETS:vcl_hit>>
}

# ============================================================
# vcl_miss - Cache miss
# ============================================================
sub vcl_miss {
    # <<WSLPROXY_SNIPPETS:vcl_miss>>
}

# ============================================================
# vcl_backend_fetch - Before fetching from backend
# ============================================================
sub vcl_backend_fetch {
    # <<WSLPROXY_SNIPPETS:vcl_backend_fetch>>
}

# ============================================================
# vcl_backend_response - Response received from backend
# ============================================================
sub vcl_backend_response {
    # Default TTL, grace, and keep from config
    set beresp.ttl = {{cache_ttl_default}}s;
    set beresp.grace = {{cache_grace}}s;
    set beresp.keep = {{cache_keep}}s;

    # <<WSLPROXY_SNIPPETS:vcl_backend_response>>
}

# ============================================================
# vcl_deliver - Before delivering response to client
# ============================================================
sub vcl_deliver {
    # Cache status headers
    if (obj.hits > 0) {
        set resp.http.X-Cache = "HIT";
    } else {
        set resp.http.X-Cache = "MISS";
    }
    set resp.http.X-Cache-Hits = obj.hits;
    set resp.http.X-Served-By = "WSLProxy-Varnish";

    # <<WSLPROXY_SNIPPETS:vcl_deliver>>
}

# ============================================================
# vcl_synth - Synthetic responses
# ============================================================
sub vcl_synth {
    # <<WSLPROXY_SNIPPETS:vcl_synth>>
}
]]

-- Health check probe block template
local HEALTH_CHECK_TEMPLATE = [[
    .probe = {
        .url = "{{health_check_url}}";
        .interval = {{health_check_interval}};
        .timeout = {{health_check_timeout}};
        .threshold = {{health_check_threshold}};
        .window = {{health_check_window}};
    }]]

-- ============================================================
-- Template Rendering
-- ============================================================

-- Render template variables: replace {{var}} with config values
function _M.render_template(template, config)
    if not template or not config then
        return template
    end

    -- Build health check block
    local health_block = ""
    if config.health_check_enabled then
        health_block = HEALTH_CHECK_TEMPLATE
        health_block = health_block:gsub("{{health_check_url}}", tostring(config.health_check_url or "/health"))
        health_block = health_block:gsub("{{health_check_interval}}", tostring(config.health_check_interval or "5s"))
        health_block = health_block:gsub("{{health_check_timeout}}", tostring(config.health_check_timeout or "2s"))
        health_block = health_block:gsub("{{health_check_threshold}}", tostring(config.health_check_threshold or 3))
        health_block = health_block:gsub("{{health_check_window}}", tostring(config.health_check_window or 5))
    end

    local rendered = template
    rendered = rendered:gsub("{{health_check_block}}", health_block)
    rendered = rendered:gsub("{{backend_host}}", tostring(config.backend_host or "127.0.0.1"))
    rendered = rendered:gsub("{{backend_port}}", tostring(config.backend_port or 80))
    rendered = rendered:gsub("{{backend_connect_timeout}}", tostring(config.backend_connect_timeout or "5s"))
    rendered = rendered:gsub("{{backend_first_byte_timeout}}", tostring(config.backend_first_byte_timeout or "30s"))
    rendered = rendered:gsub("{{backend_between_bytes_timeout}}", tostring(config.backend_between_bytes_timeout or "5s"))
    rendered = rendered:gsub("{{cache_ttl_default}}", tostring(config.cache_ttl_default or 120))
    rendered = rendered:gsub("{{cache_grace}}", tostring(config.cache_grace or 3600))
    rendered = rendered:gsub("{{cache_keep}}", tostring(config.cache_keep or 7200))

    return rendered
end

-- ============================================================
-- Snippet Injection
-- ============================================================

-- Sort snippets: by priority (ascending), then by name (alphabetical) as tiebreaker
local function sort_snippets(snippets)
    local sorted = {}
    for _, s in ipairs(snippets) do
        table.insert(sorted, s)
    end
    table.sort(sorted, function(a, b)
        local pa = tonumber(a.priority) or 100
        local pb = tonumber(b.priority) or 100
        if pa ~= pb then
            return pa < pb
        end
        return (a.name or "") < (b.name or "")
    end)
    return sorted
end

-- Group snippets by hook_point, returning only enabled snippets
local function group_snippets_by_hook(snippets)
    local groups = {}
    for _, snippet in ipairs(snippets) do
        if snippet.enabled ~= false then
            local hook = snippet.hook_point
            if hook then
                if not groups[hook] then
                    groups[hook] = {}
                end
                table.insert(groups[hook], snippet)
            end
        end
    end

    -- Sort each group
    for hook, group in pairs(groups) do
        groups[hook] = sort_snippets(group)
    end

    return groups
end

-- Inject snippets at marker positions in VCL text
-- Markers: # <<WSLPROXY_SNIPPETS:{hook_point}>>
function _M.inject_snippets(vcl_text, snippets)
    if not vcl_text then
        return vcl_text
    end
    if not snippets or #snippets == 0 then
        -- Remove markers when no snippets
        vcl_text = vcl_text:gsub("%s*# <<WSLPROXY_SNIPPETS:%w+>>", "")
        return vcl_text
    end

    local groups = group_snippets_by_hook(snippets)

    -- Replace each marker with its snippets
    vcl_text = vcl_text:gsub("([ \t]*)# <<WSLPROXY_SNIPPETS:(%w+)>>", function(indent, hook_point)
        local hook_snippets = groups[hook_point]
        if not hook_snippets or #hook_snippets == 0 then
            return ""
        end

        local lines = {}
        table.insert(lines, indent .. "### BEGIN SNIPPETS: " .. hook_point)

        for _, snippet in ipairs(hook_snippets) do
            local name = snippet.name or "unnamed"
            local priority = tostring(snippet.priority or 100)

            table.insert(lines, indent .. "### SNIPPET: " .. name .. " (priority: " .. priority .. ")")

            -- Indent snippet content to match context
            for line in snippet.content:gmatch("[^\r\n]+") do
                table.insert(lines, indent .. line)
            end

            table.insert(lines, indent .. "### END SNIPPET: " .. name)
        end

        table.insert(lines, indent .. "### END SNIPPETS: " .. hook_point)

        return table.concat(lines, "\n")
    end)

    return vcl_text
end

-- ============================================================
-- Full VCL Assembly
-- ============================================================

-- Assemble complete VCL from config and snippets
function _M.assemble(server_name, config, snippets)
    if not config then
        return nil, "Config is required"
    end

    -- Start with base template
    local template = _M.BASE_TEMPLATE

    -- Render template variables
    local vcl = _M.render_template(template, config)

    -- Inject snippets
    snippets = snippets or {}
    vcl = _M.inject_snippets(vcl, snippets)

    -- Add generation header
    local header = string.format(
        "# VCL generated by WSLProxy Varnish Manager\n" ..
        "# Server: %s\n" ..
        "# Generated: %s\n" ..
        "# Snippets: %d\n\n",
        tostring(server_name),
        os.date("%Y-%m-%dT%H:%M:%SZ", os.time()),
        #snippets
    )

    return header .. vcl, nil
end

-- ============================================================
-- VCL Validation
-- ============================================================

-- Validate VCL syntax by running varnishd -C -f <file>
-- Returns: ok (boolean), output (string)
function _M.validate_vcl(vcl_content)
    if not vcl_content or vcl_content == "" then
        return false, "VCL content is empty"
    end

    -- Write VCL to temp file
    local tmp_path = "/tmp/wslproxy_vcl_validate_" .. os.time() .. ".vcl"
    local file, err = io.open(tmp_path, "wb")
    if not file then
        return false, "Failed to write temp VCL file: " .. tostring(err)
    end
    file:write(vcl_content)
    file:close()

    -- Run varnishd -C -f to compile-check
    local handle = io.popen("varnishd -C -f " .. tmp_path .. " 2>&1")
    local output = ""
    if handle then
        output = handle:read("*all")
        handle:close()
    end

    -- Clean up temp file
    os.remove(tmp_path)

    -- Check for success
    -- varnishd -C outputs compiled VCL on success, error messages on failure
    local is_valid = not output:match("^Message from VCC%-compiler") and
                     not output:match("^VCL compilation failed") and
                     not output:match("^VCL%.Errstatus")

    -- If output is empty, varnishd might not be installed
    if output == "" then
        return false, "varnishd not found or no output. Ensure Varnish is installed."
    end

    if is_valid then
        return true, "VCL syntax is valid"
    else
        return false, output
    end
end

-- ============================================================
-- Deploy Helpers
-- ============================================================

-- Generate a VCL label for deployment (used with vcl.load/vcl.use)
function _M.generate_vcl_label(server_name)
    local timestamp = os.date("%Y%m%d%H%M%S", os.time())
    -- Sanitize server_name for use in VCL label (alphanumeric + underscore only)
    local safe_name = server_name:gsub("[^%w]", "_")
    return "wslproxy_" .. safe_name .. "_" .. timestamp
end

-- Load and activate VCL via varnishadm
-- Returns: ok (boolean), output (string), label (string)
function _M.deploy_vcl(vcl_path, admin_address, label)
    admin_address = admin_address or "127.0.0.1:6082"
    label = label or _M.generate_vcl_label("deploy")

    -- Load the new VCL
    local load_cmd = string.format("varnishadm -T %s vcl.load %s %s 2>&1",
        admin_address, label, vcl_path)
    local handle = io.popen(load_cmd)
    local load_output = ""
    if handle then
        load_output = handle:read("*all")
        handle:close()
    end

    if load_output:match("[Ee]rror") or load_output:match("[Ff]ailed") then
        return false, "VCL load failed: " .. load_output, label
    end

    -- Activate the new VCL
    local use_cmd = string.format("varnishadm -T %s vcl.use %s 2>&1",
        admin_address, label)
    handle = io.popen(use_cmd)
    local use_output = ""
    if handle then
        use_output = handle:read("*all")
        handle:close()
    end

    if use_output:match("[Ee]rror") or use_output:match("[Ff]ailed") then
        return false, "VCL activate failed: " .. use_output, label
    end

    return true, "VCL deployed and activated: " .. label, label
end

-- Purge cache via varnishadm
function _M.purge_cache(admin_address, url_pattern)
    admin_address = admin_address or "127.0.0.1:6082"
    url_pattern = url_pattern or ".*"

    local cmd = string.format('varnishadm -T %s "ban req.url ~ %s" 2>&1',
        admin_address, url_pattern)
    local handle = io.popen(cmd)
    local output = ""
    if handle then
        output = handle:read("*all")
        handle:close()
    end

    local success = not output:match("[Ee]rror") and not output:match("[Ff]ailed")
    return success, output
end

return _M
