FROM dixajangid/selenium-base:latest

WORKDIR /app

# Copy the repository files to the container

RUN apt-get install bash

COPY . /app

CMD ["pytest -v -s --alluredir=/app/testresults ; allure generate --clean /app/testresults -o /app/testreports ; chmod -R 777 /app/testreports"]
